openapi:
  server-url: https://netand.store

spring:
  datasource:
    url: ENC(UoECUY5gc3ibrJcBDNn9AhTAGb4gNBpfbrh/Y0RbBR2n+QBrXP9B2o9yTrykkHiZazMVL2aMHADM/wWdP06X0X/orz/RNxkBWcWv6oxrFHgsauIgTzOkEvnLCmL36m1mwC1Vhhech0mVzHhH1sLLr+dHbnorLW/IfTBrS6LDGGqDbocZDGDNPnVcws70Yg0OgjYDBlgvWGbkftqYDuSy9w==)
    username: ENC(qJr/HtJ2rlRABtb98cX/PA==)
    password: ENC(dNK17EYQjBVeAcsZnsn7kqAGg5q6Jjo4)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
    generate-ddl: true

  sql:
    init:
      mode: always

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  data:
    redis:
      host: redis
      port: 6379
      password: ENC(/3s0KzY2txyvZf2+NhMa4495FdbMT4sv)

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(rJZjJpiqvSvvJtaBUj7ynl4A1nJDQbk5QTk1PhW2yUg=)
    password: ENC(ze6ddLHadAfsIjV/rh+W0TjOCBMCJ/Nt88bBKiiizjY=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

jwt:
  secret: ENC(tAceO54tTCOPQ5UoHSoywdlcJDldRYYCOD3ZMemOky0u8mmH947onqVGNUaZbZT5EVdwOFqnkl8=)

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}